FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
RUN dotnet new web -n AuthApiKey
COPY src/Program.cs /src/AuthApiKey/Program.cs
WORKDIR /src/AuthApiKey
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "AuthApiKey.dll"]
